server:
  port: 8080

spring:
  application:
    name: hermes
  #  main:
  #    lazy-initialization: true
  #  jmx:
  #    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:55432/smart_enough_city
    username: backend_user
    password: dev_backend_user_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
loki:
  url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
  timeoutMs: 5000