apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-inference-engine
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: inference-engine
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: inference-engine
    spec:
      containers:
        - name: inference-engine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          - name: APP_ENV
            value: "prod"
          - name: DATA_ENGINE_URL
            value: {{ .Values.env.dataEngineUrl | quote }}
          - name: NOTIFICATION_API_URL
            value: {{ .Values.env.notificationApiUrl | quote }}
          - name: HTTP_TIMEOUT
            value: {{ .Values.env.httpTimeout | quote }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
