image:
  repository: inference-engine
  tag: dev
  pullPolicy: Never

replicaCount: 1

service:
  type: ClusterIP
  port: 8000

env:
  dataEngineUrl: "http://sec-data-handler:8080/api/v1/recommendation-engine/indicators/query"
  notificationApiUrl: "http://sec-hermes:8081/api/v1/notification"
  httpTimeout: "30"

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "2000m"
    memory: "2Gi"

labels:
  app.kubernetes.io/name: inference-engine
  app.kubernetes.io/component: api-server
  app.kubernetes.io/part-of: smart-enough-city
