apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"sec-keycloak-allow-ingress-from-hermes","namespace":"dev"},"spec":{"ingress":[{"from":[{"podSelector":{"matchLabels":{"app.kubernetes.io/instance":"sec","app.kubernetes.io/name":"hermes"}}}],"ports":[{"port":8080,"protocol":"TCP"}]}],"podSelector":{"matchLabels":{"app.kubernetes.io/instance":"sec","app.kubernetes.io/name":"keycloak"}},"policyTypes":["Ingress"]}}
  creationTimestamp: "2026-01-30T22:12:09Z"
  generation: 1
  name: sec-keycloak-allow-ingress-from-hermes
  namespace: dev
  resourceVersion: "1769811129378783001"
  uid: 7e7c6916-df36-4b66-a231-db73f252eb3c
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: sec
          app.kubernetes.io/name: hermes
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: sec
      app.kubernetes.io/name: keycloak
  policyTypes:
  - Ingress
