apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-data-handler
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- toYaml .Values.labels | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  {{- if .Values.timeZone }}
  timeZone: {{ .Values.timeZone | quote }}
  {{- end }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 45
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 55
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: {{ .Release.Name }}
{{- toYaml .Values.labels | nindent 12 }}
        spec:
          restartPolicy: Never
          terminationGracePeriodSeconds: 10
          containers:
            - name: data-handler
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
{{- toYaml .Values.resources | nindent 16 }}
              env:
                - name: DB_HOST
                  value: {{ .Values.global.db.host | default (printf "%s-postgresql" .Release.Name) | quote }}
                - name: DB_PORT
                  value: {{ .Values.global.db.port | quote }}
                - name: DB_NAME
                  value: {{ .Values.global.db.name | quote }}
                - name: DB_DATA_HANDLER_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secrets.dbUser.name | quote }}
                      key: DB_DATA_HANDLER_USER
                - name: DB_DATA_HANDLER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secrets.dbUser.name | quote }}
                      key: DB_DATA_HANDLER_PASSWORD
                - name: DB_DATA_HANDLER_SCHEMA
                  value: {{ .Values.global.db.schemas.dataHandlerSchema | quote }}
